#!/bin/sh

# By running the files one at a time we get around the
# get-comics/link_check function redeclaration warnings
echo "Running sparse on files..."
for f in *.[ch]; do sparse $f; done

echo "Running checkpatch on files..."
for f in *.[ch]; do
    [ $f = JSON_parser.c -o $f = JSON_parser.h ] && continue
    checkpatch --file $f | fgrep -q "no obvious style problems" || echo "$f"
done
