#!/bin/sh

echo "Running sparse on files..."
sparse -I/usr/include/libxml2 -DWANT_XML -DWANT_JSON *.[ch]

echo "Running checkpatch on files..."
for f in *.[ch]; do
    checkpatch --file $f | fgrep -q "no obvious style problems" || echo "$f"
done
